### ISSUE TITLE
Uncaught SyntaxError: Unexpected token \ in JSON at position 50

### ISSUE THREAD

**Issue by Psinergy** [live-composer/live-composer-page-builder#450] opened 2016-12-21 17:11 UTC
Just upgraded to the newest version, and now getting this:

JavaScript error detected in a third-party plugin
Uncaught SyntaxError: Unexpected token \ in JSON at position 50
File "https://www.xxxxxxxxxxxxxx/wp-admin/admin.php?page=livecomposer_editor&page_id=", line 1, char 51

**Comment by Psinergy** [comment] 2016-12-21 17:13
Then, on another site, edit one module/row, etc... then after that cannot change anything else on the page.

**Comment by xdima92x** [comment] 2017-01-10 09:14
Hi @Psinergy The error is coming from a third-party plugin. Please disable all the third-party plugins one by one until you find the one causing the troubles. Let me know the results, please if it helped :)

**Comment by xdima92x** [comment] 2017-02-02 09:33
Hi @Psinergy I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.

**Closed by xdima92x** 2017-02-02 09:33 UTC
Labels: js, needs answer

**Comment by RobertShippey** [comment] 2017-04-04 10:19
I think I'm having the same issue:

````
JavaScript error detected in a third-party plugin
Uncaught SyntaxError: Unexpected token u in JSON at position 0
File "http://www.mysite.co.uk/?page_id=123&dslc", line 1, char 1
````

The problem is coming from the plugin "Feed Them Social" when using their 'Combined Streams' add-on. I create a blank page in LC and simply add a shortcode into the shortcode module into the page. After saving it works fine, but when you open the editor back up again that error is waiting for you and you can't change anything in the editor.

Feed Them Social works, just not when used from within Live Composer.
