### ISSUE TITLE
Stylesheets not being enqueued all of the sudden???

### ISSUE THREAD

**Issue by jessicahawkins3344** [live-composer/live-composer-page-builder#340] opened 2016-10-18 12:09 UTC
When building a site today - I suddenly noticed that several modules just stopped working correctly. I looked into the dev tools and compared a page where everything was functioning properly to the new pages (site wide) with module problems and noticed that the stylesheets are not being called for some reason? PLEASE HELP! 

Example, notice the modules.css being called here:
<img width="1155" alt="screenshot 2016-10-18 07 06 05" src="https://cloud.githubusercontent.com/assets/5214397/19476932/608a1518-9501-11e6-9061-bd6b20ed19ad.png">

Problem, same page now having issues with the tabs module with - inspecting same element and no modules.css is being used: 
<img width="1262" alt="screenshot 2016-10-18 07 08 41" src="https://cloud.githubusercontent.com/assets/5214397/19477006/c0a9ac06-9501-11e6-9687-b30120ff5f70.png">

**Comment by lumberman** [comment] 2016-10-21 05:22
Hi Jessica,

Is it happening only when you refresh the page in Chrome browser? If so, it's a known bug in the browser we can do nothing about. It will be fixed with the next browser update. For now, click enter in page address to refresh the page properly.

Please reopen this conversation if I'm wrong and your problem isn't caused by the page refresh.

**Closed by lumberman** 2016-10-21 05:22 UTC
